version: "3"
services:
  glances:
    build : ${PWD}/requirements/bonus/glances
    container_name: glances
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart : unless-stopped
    networks :
      - docker_net
  webpage:
    build : ${PWD}/requirements/bonus/static_webpage
    container_name: webpage
    networks :
      - docker_net
    restart : unless-stopped
  mariadb :
    build:
      context: ${PWD}/requirements/mariadb/
      args:
        - DB_NAME=mariadb
        - newUser=hboukili
        - Newpassword=fes123
        - USER_WP=USER
        - PASSWORD_WP=123
        - email=hm.boukiili97@gmail.com
        - EMAIL_WP=user@gmail.com
        - title=inception
    container_name: mariadb
    env_file: .env
    volumes: 
      - mariadb:/var/lib/mysql
    restart : unless-stopped
    networks:
    - docker_net
  adminer :
    depends_on:
      - mariadb
    build : ${PWD}/requirements/bonus/adminer
    container_name : adminer
    networks : 
      - docker_net
  wordpress:
    depends_on:
      - mariadb
    build: 
      context: ${PWD}/requirements/wordpress/
      args:
        - DB_NAME=mariadb
        - newUser=hboukili
        - Newpassword=fes123
        - USER_WP=USER
        - PASSWORD_WP=123
        - email=hm.boukiili97@gmail.com
        - EMAIL_WP=user@gmail.com
        - title=inception
    container_name: wordpress
    env_file:
      -  .env
    volumes:
      - wordpress:/var/www/html
    restart : unless-stopped
    networks:
    - docker_net 
  nginx:
    depends_on:
      - adminer
    build: ${PWD}/requirements/nginx
    container_name: nginx
    volumes:
      - wordpress:/var/www/html
    ports:
      - '443:443'
    restart : unless-stopped
    networks:
    - docker_net
  redis :
    build : ${PWD}/requirements/bonus/redis
    depends_on:
      - wordpress
    container_name : redis
    networks :
      - docker_net
volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/hboukili/data/DB
  wordpress :
    driver : local
    driver_opts :
      o: bind
      type : none
      device : /home/hboukili/data/wordpress
networks:
  docker_net:
    driver: bridge
